CREATE TABLE CUSTOMER(
CUSTID VARCHAR2(20) PRIMARY KEY,
PASSWORD VARCHAR2(20) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL,
DIVISION VARCHAR2(20) NOT NULL,
NAME VARCHAR2(30) NOT NULL,
IDNO VARCHAR2(20), 
ADDRESS VARCHAR2(100)
);

CREATE TABLE PERSONAL_INFORMATION(
	PI_SEQ VARCHAR2(10) PRIMARY KEY,
	PI_FRIST_NAME VARCHAR2(20) NOT NULL, 
	PI_LAST_NAME VARCHAR2(30) NOT NULL,
	PI_SEX VARCHAR2(1) NOT NULL,
	PI_AGE NUMBER NOT NULL,
	PI_JOB VARCHAR2(100) NOT NULL,
	PI_FIELD VARCHAR2(300) NOT NULL,
	PI_SCHOOL VARCHAR2(100) NOT NULL,
	PI_FAMILY VARCHAR2(100) NOT NULL,
	PI_DEPT VARCHAR2(60) NOT NULL, 
	PI_POSITION VARCHAR2(60) NOT NULL,
	PI_HOBBY VARCHAR2(60) NOT NULL,
	PI_BIRTHPLACE VARCHAR2(300) NOT NULL,
	PI_MAJOR VARCHAR2(60) NOT NULL,
	PI_SALARY NUMBER NOT NULL,
	PI_HIREDATE VARCHAR2(10) NOT NULL,
	PI_CAREER_ONE VARCHAR2(1000) NOT NULL,
	PI_CAREER_TWO VARCHAR2(1000), 
	PI_CAREER_THREE VARCHAR2(1000),
	PI_LICENSE_ONE VARCHAR2(1000) NOT NULL,
	PI_LICENSE_TWO VARCHAR2(1000),
	PI_LICENSE_THREE VARCHAR2(1000) ,
	PI_COMP_PHONE VARCHAR2(30) NOT NULL,
	PI_PHONE_ONE VARCHAR2(30) NOT NULL,
	PI_PHONE_TWO VARCHAR2(30),
	PI_ZIPCODE VARCHAR2(10) NOT NULL,
	PI_ADDRESS VARCHAR2(1000) NOT NULL,
	PI_ADDRESS_DETAIL VARCHAR2(3000) NOT NULL,
	PI_EMAIL VARCHAR2(30) NOT NULL,
	PI_FAX VARCHAR2(30) NOT NULL,
	PI_HOMEPAGE VARCHAR2(100) NOT NULL,
	PI_COUNT NUMBER, 
	PI_DELETEFLAG VARCHAR2(1) NOT NULL,
	PI_PUBLICFLAG VARCHAR2(1) NOT NULL,
	PI_INDATE VARCHAR2(10) NOT NULL,
	PI_LDATE VARCHAR2(10)
);

SELECT * FROM PERSONAL_INFORMATION WHERE PI_SEX LIKE 0;

SELECT * FROM PERSONAL_INFORMATION WHERE PI_FRIST_NAME = '성' AND PI_SEX = 0 AND PI_PUBLICFLAG =0 

CREATE SEQUENCE PI_SEQ start with 1 increment by 1;   